---
title: "Visualization Part1"
output: github_document
---

```{r}
library(tidyverse) ##use ggplot 2
library(ggridges)
```

## Load the dataset

NOAA weather data: use rnoaa::meteo_pull_monitors to download the dataset
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"), #specify the three weathersites
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"), 
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())


weather_df
```

##  Scatterplots

Creat first scatterplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()

#OR 
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

### Save and edit a plot object
```{r}
plot_weather = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) 

plot_weather + geom_point()

```
### color scatterplot
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name)) +
  geom_smooth(se = FALSE)

# OR
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point() +
  geom_smooth(se = FALSE)

```

### add curve
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  geom_smooth(se = FALSE)


```

### seperate the scatterplot
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)

# OR
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .2) +
  geom_smooth(se = FALSE) + 
    facet_grid(. ~ name)
```
add curve
```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

### density curve
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_density2d() +
  geom_point(alpha = .3) 
```

### some small notes

How many geoms have to exist?
You can have whatever geoms you want.

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .2) +
  geom_smooth(se = FALSE) 
```


```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(
    tmax_fahr = tmax * (9 / 5) + 32,
    tmin_fahr = tmin * (9 / 5) + 32) %>% 
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
  geom_point(alpha = .5) + 
  geom_smooth(method = "lm", se = FALSE)
```

